### ISSUE TITLE
Cannot parse file for LRS pager Sub-GHz

### ISSUE THREAD

**Issue by unred4cted** [RocketGod-git/Flipper_Zero#3]
Every time I try to open the Sub-GHz file for the LRS Restaurant Pagers my flipper always says **cannot parse file.** 
Here is a list of things I have tried:
I have uploaded the file directly to the sd card.
I have used qflipper to upload the file to flipper
Have tried the flipper app for iOS.
I have downloaded entire repository in zip form.
Then I tried downloading the .sub files by clicking view raw then saving to computer.

I have read online that it may have to do with the firmware version the flipper was running when the file was originally made.

After all these things it still says same error. Could anybody please offer any help. Or is it a problem with the file.

**Comment by RocketGod-git** [comment]
Most likely, you're not using a firmware which has unlocked the frequency you need to be using.
What firmware are you using?

**Comment by unred4cted** [comment]
I am using the official firmware V0.80.1. Is there a custom firmware I need to use?

**Comment by RocketGod-git** [comment]
Yes. Here's an invite link to my Discord server where we can help you easier. 

[The Pirates' Plunder](https://discord.gg/thepirates)
